stages:
   - build
   - test
	
build:
   stage: build
   image: maven:3-jdk-11
   script:
      -cd api-automation
      -mvn -Dmaven.test.skip=true clean package
		
test:
   stage: test
   image: maven:3-jdk-11
   script:
      - cd api-automation
      - mvn test